### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by nirvdrum** [reinh/statsd#47]
Fortunately this project isn't too large in terms of commits, but it'd be a lot easier to tell what changed from release-to-release if there were a changelog.  It'd also be a good place to expound upon anything that was only hinted at briefly in the commit message.

**Comment by raggi** [comment]
Sorry, we're leaning on bundlers gem_tasks for releases, which doesn't do anything useful when writing tag messages, otherwise I'd put it in the tag data and the github releases page would display the right stuff.

**Comment by raggi** [comment]
Added notes to the release using the UI: https://github.com/reinh/statsd/releases/tag/v1.3.0
