### ISSUE TITLE
Arbitrary metric name parsing

### ISSUE THREAD

**Issue by erez-rabih** [reinh/statsd#58]
Hi,

In line 387 of file lib/statsd.rb we replace "::" with "." to have directory structure which resembles the ruby module scoping.

While I understand the logic behind this decision, I'd like to propose to make it configurable and not mandatory. I for example, would like to replace "::" with "-" and not "." to have flat metric hierarchy.

If this idea is accepted I'm also willing to make a PR.

I'd be happy to hear your thoughts.

**Comment by raggi** [comment]
The most common graphite setups use a period for directory separation, but making this configurable seems reasonable.
