### ISSUE TITLE
Proposal to cut a new release

### ISSUE THREAD

**Issue by sfgeorge** [reinh/statsd#63]
Hello,

I'm finding this gem for StatsD very helpful.  I noticed that a new release has not been cut since 1.2.1 in 2013, but there are definitely [some great goodies on the master branch that have not yet been released](https://github.com/reinh/statsd/compare/v1.2.1...master).  The added Admin ability to delete stats would certainly be helpful, for one.  Is there anything that needs to be finalized / fixed before cutting a new release?  Let me know if there's anything I can do to help.  Thanks very much.

**Comment by reinh** [comment]
:+1: You aren't the first to ask for this. @raggi, PTAL. Any reason we can't cut a new minor release from `master`?

**Comment by dustMason** [comment]
Please please please :D

**Comment by raggi** [comment]
Sorry, I'm not going to be able to do this in the near term.

**Comment by raggi** [comment]
1.3.0 just released
